import { createTheme, createThemeContract } from "@vanilla-extract/css";

export const themeVars = createThemeContract({
  color: {
    primary: null,
    secondary: null,
    title: null,
    subtitle: null,
    active: null,
    disabled: null,
    clicked: null,
    background: null,
    default: null,
  },
  space: {
    none: null,
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    "2xl": null,
    "3xl": null,
    "4xl": null,
  },
  radius: {
    none: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    full: null,
  },

  shadow: {
    sm: null,
    md: null,
    lg: null,
    focus: null,
  },
  motion: {
    durationFast: null,
    durationNormal: null,
    durationSlow: null,
    easingStandard: null,
    easingEmphasized: null,
  },
  zIndex: {
    base: null,
    sticky: null,
    dropdown: null,
    overlay: null,
    modal: null,
    toast: null,
  },
});

export const lightTheme = createTheme(themeVars, {
  color: {
    primary: "#5A81FA",
    secondary: "#2B308B",
    title: "#1F1F1F",
    subtitle: "#696E82",
    active: "#CEDEFF",
    disabled: "#D4DAED",
    clicked: "#F2F4FF",
    background: "#F8F9FD",
    default: "#FFFFFF",
  },
  space: {
    none: "0",
    xxs: "0.125rem",
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    "2xl": "2rem",
    "3xl": "3rem",
    "4xl": "4rem",
  },
  radius: {
    none: "0",
    sm: "0.25rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
    full: "9999px",
  },
  shadow: {
    sm: "0 1px 2px rgba(15, 23, 42, 0.08)",
    md: "0 4px 12px rgba(15, 23, 42, 0.10)",
    lg: "0 12px 32px rgba(15, 23, 42, 0.16)",
    focus: "0 0 0 3px rgba(37, 99, 235, 0.28)",
  },
  motion: {
    durationFast: "120ms",
    durationNormal: "180ms",
    durationSlow: "260ms",
    easingStandard: "cubic-bezier(0.2, 0, 0, 1)",
    easingEmphasized: "cubic-bezier(0.2, 0, 0, 1)",
  },
  zIndex: {
    base: "0",
    sticky: "10",
    dropdown: "1000",
    overlay: "1100",
    modal: "1200",
    toast: "1300",
  },
});

export const darkTheme = createTheme(themeVars, {
  color: {
    primary: "#7A9CFF",
    secondary: "#4C54C7",
    title: "#E6E6E6",
    subtitle: "#A0A6BD",
    active: "#3A4060",
    disabled: "#6F7896",
    clicked: "#2A2E45",
    background: "#1E1E1E",
    default: "#121212",
  },
  space: {
    none: "0",
    xxs: "0.125rem",
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    "2xl": "2rem",
    "3xl": "3rem",
    "4xl": "4rem",
  },
  radius: {
    none: "0",
    sm: "0.25rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
    full: "9999px",
  },
  shadow: {
    sm: "0 1px 2px rgba(2, 6, 23, 0.35)",
    md: "0 6px 16px rgba(2, 6, 23, 0.45)",
    lg: "0 16px 40px rgba(2, 6, 23, 0.55)",
    focus: "0 0 0 3px rgba(96, 165, 250, 0.28)",
  },
  motion: {
    durationFast: "120ms",
    durationNormal: "180ms",
    durationSlow: "260ms",
    easingStandard: "cubic-bezier(0.2, 0, 0, 1)",
    easingEmphasized: "cubic-bezier(0.2, 0, 0, 1)",
  },
  zIndex: {
    base: "0",
    sticky: "10",
    dropdown: "1000",
    overlay: "1100",
    modal: "1200",
    toast: "1300",
  },
});
