import { createTheme, createThemeContract } from "@vanilla-extract/css";
import { pretendardFamily } from "@boo/font";

export const themeVars = createThemeContract({
  color: {
    background: null,
    backgroundElevated: null,
    backgroundSubtle: null,
    backgroundMuted: null,
    surface: null,
    surfaceHover: null,
    surfacePressed: null,
    border: null,
    borderStrong: null,
    textPrimary: null,
    textSecondary: null,
    textTertiary: null,
    textInverse: null,
    textDisabled: null,
    primary: null,
    primaryHover: null,
    primaryPressed: null,
    primaryForeground: null,
    secondary: null,
    secondaryHover: null,
    secondaryPressed: null,
    secondaryForeground: null,
    success: null,
    warning: null,
    danger: null,
    info: null,
    focusRing: null,
    scrim: null,
  },
  space: {
    none: null,
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    "2xl": null,
    "3xl": null,
    "4xl": null,
  },
  radius: {
    none: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    full: null,
  },
  font: {
    fontFamily: null,
    sizeXs: null,
    sizeSm: null,
    sizeMd: null,
    sizeLg: null,
    sizeXl: null,
    size2xl: null,
    weightRegular: null,
    weightMedium: null,
    weightSemibold: null,
    weightBold: null,
    lineHeightTight: null,
    lineHeightNormal: null,
    lineHeightRelaxed: null,
    trackingTight: null,
    trackingNormal: null,
  },
  shadow: {
    sm: null,
    md: null,
    lg: null,
    focus: null,
  },
  motion: {
    durationFast: null,
    durationNormal: null,
    durationSlow: null,
    easingStandard: null,
    easingEmphasized: null,
  },
  zIndex: {
    base: null,
    sticky: null,
    dropdown: null,
    overlay: null,
    modal: null,
    toast: null,
  },
});

export const lightTheme = createTheme(themeVars, {
  color: {
    background: "#ffffff",
    backgroundElevated: "#f8fafc",
    backgroundSubtle: "#f1f5f9",
    backgroundMuted: "#e2e8f0",
    surface: "#ffffff",
    surfaceHover: "#f8fafc",
    surfacePressed: "#e2e8f0",
    border: "#cbd5e1",
    borderStrong: "#94a3b8",
    textPrimary: "#0f172a",
    textSecondary: "#334155",
    textTertiary: "#64748b",
    textInverse: "#ffffff",
    textDisabled: "#94a3b8",
    primary: "#2563eb",
    primaryHover: "#1d4ed8",
    primaryPressed: "#1e40af",
    primaryForeground: "#ffffff",
    secondary: "#475569",
    secondaryHover: "#334155",
    secondaryPressed: "#1e293b",
    secondaryForeground: "#ffffff",
    success: "#16a34a",
    warning: "#d97706",
    danger: "#dc2626",
    info: "#0284c7",
    focusRing: "rgba(37, 99, 235, 0.35)",
    scrim: "rgba(15, 23, 42, 0.5)",
  },
  space: {
    none: "0",
    xxs: "0.125rem",
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    "2xl": "2rem",
    "3xl": "3rem",
    "4xl": "4rem",
  },
  radius: {
    none: "0",
    sm: "0.25rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
    full: "9999px",
  },
  font: {
    fontFamily: pretendardFamily,
    sizeXs: "0.75rem",
    sizeSm: "0.875rem",
    sizeMd: "1rem",
    sizeLg: "1.125rem",
    sizeXl: "1.25rem",
    size2xl: "1.5rem",
    weightRegular: "400",
    weightMedium: "500",
    weightSemibold: "600",
    weightBold: "700",
    lineHeightTight: "1.2",
    lineHeightNormal: "1.5",
    lineHeightRelaxed: "1.75",
    trackingTight: "-0.02em",
    trackingNormal: "0",
  },
  shadow: {
    sm: "0 1px 2px rgba(15, 23, 42, 0.08)",
    md: "0 4px 12px rgba(15, 23, 42, 0.10)",
    lg: "0 12px 32px rgba(15, 23, 42, 0.16)",
    focus: "0 0 0 3px rgba(37, 99, 235, 0.28)",
  },
  motion: {
    durationFast: "120ms",
    durationNormal: "180ms",
    durationSlow: "260ms",
    easingStandard: "cubic-bezier(0.2, 0, 0, 1)",
    easingEmphasized: "cubic-bezier(0.2, 0, 0, 1)",
  },
  zIndex: {
    base: "0",
    sticky: "10",
    dropdown: "1000",
    overlay: "1100",
    modal: "1200",
    toast: "1300",
  },
});

export const darkTheme = createTheme(themeVars, {
  color: {
    background: "#020617",
    backgroundElevated: "#0f172a",
    backgroundSubtle: "#111827",
    backgroundMuted: "#1e293b",
    surface: "#0f172a",
    surfaceHover: "#1e293b",
    surfacePressed: "#334155",
    border: "#334155",
    borderStrong: "#475569",
    textPrimary: "#f8fafc",
    textSecondary: "#cbd5e1",
    textTertiary: "#94a3b8",
    textInverse: "#0f172a",
    textDisabled: "#64748b",
    primary: "#60a5fa",
    primaryHover: "#3b82f6",
    primaryPressed: "#2563eb",
    primaryForeground: "#020617",
    secondary: "#94a3b8",
    secondaryHover: "#cbd5e1",
    secondaryPressed: "#e2e8f0",
    secondaryForeground: "#020617",
    success: "#4ade80",
    warning: "#fbbf24",
    danger: "#f87171",
    info: "#38bdf8",
    focusRing: "rgba(96, 165, 250, 0.35)",
    scrim: "rgba(2, 6, 23, 0.68)",
  },
  space: {
    none: "0",
    xxs: "0.125rem",
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    "2xl": "2rem",
    "3xl": "3rem",
    "4xl": "4rem",
  },
  radius: {
    none: "0",
    sm: "0.25rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
    full: "9999px",
  },
  font: {
    fontFamily: pretendardFamily,
    sizeXs: "0.75rem",
    sizeSm: "0.875rem",
    sizeMd: "1rem",
    sizeLg: "1.125rem",
    sizeXl: "1.25rem",
    size2xl: "1.5rem",
    weightRegular: "400",
    weightMedium: "500",
    weightSemibold: "600",
    weightBold: "700",
    lineHeightTight: "1.2",
    lineHeightNormal: "1.5",
    lineHeightRelaxed: "1.75",
    trackingTight: "-0.02em",
    trackingNormal: "0",
  },
  shadow: {
    sm: "0 1px 2px rgba(2, 6, 23, 0.35)",
    md: "0 6px 16px rgba(2, 6, 23, 0.45)",
    lg: "0 16px 40px rgba(2, 6, 23, 0.55)",
    focus: "0 0 0 3px rgba(96, 165, 250, 0.28)",
  },
  motion: {
    durationFast: "120ms",
    durationNormal: "180ms",
    durationSlow: "260ms",
    easingStandard: "cubic-bezier(0.2, 0, 0, 1)",
    easingEmphasized: "cubic-bezier(0.2, 0, 0, 1)",
  },
  zIndex: {
    base: "0",
    sticky: "10",
    dropdown: "1000",
    overlay: "1100",
    modal: "1200",
    toast: "1300",
  },
});
